#!/bin/sh

set -e

trap 'echo "Fail!"' ERR

rm -rf circuits_partitioned
echo "Partitioning circuits..."
python3 circuit_scripts/partition_circuits.py
echo "Post-processing partitions..."
python3 circuit_scripts/partition_postprocessor.py
rm -rf parsetab.py # temp file generated by pyverilog
echo "Success!"